sensor:
  # EG4 Lifepower4
  - unique_id: "bms_lifepower4_pack_2_voltage_pack"
    name: "bms_lifepower4_pack_2_voltage"
    state_topic: "bms_lifepower4/pack_2/v_pack"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_voltage_pack"
    name: "bms_lifepower4_pack_3_voltage"
    state_topic: "bms_lifepower4/pack_3/v_pack"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_current"
    name: "bms_lifepower4_pack_2_current"
    state_topic: "bms_lifepower4/pack_2/i_pack"
    unit_of_measurement: "A"

  - unique_id: "bms_lifepower4_pack_3_current"
    name: "bms_lifepower4_pack_3_current"
    state_topic: "bms_lifepower4/pack_3/i_pack"
    unit_of_measurement: "A"

  - unique_id: "bms_lifepower4_pack_2_power"
    name: "bms_lifepower4_pack_2_power"
    state_topic: "bms_lifepower4/pack_2/power"
    unit_of_measurement: "W"

  - unique_id: "bms_lifepower4_pack_3_power"
    name: "bms_lifepower4_pack_3_power"
    state_topic: "bms_lifepower4/pack_3/power"
    unit_of_measurement: "W"

  - unique_id: "bms_lifepower4_pack_2_soc"
    name: "bms_lifepower4_pack_2_state_of_charge"
    state_topic: "bms_lifepower4/pack_2/soc"

  - unique_id: "bms_lifepower4_pack_3_soc"
    name: "bms_lifepower4_pack_3_state_of_charge"
    state_topic: "bms_lifepower4/pack_3/soc"

  - unique_id: "bms_lifepower4_pack_2_capacity"
    name: "bms_lifepower4_pack_2_capacity"
    state_topic: "bms_lifepower4/pack_2/i_design_cap"
    unit_of_measurement: "Ah"

  - unique_id: "bms_lifepower4_pack_3_capacity"
    name: "bms_lifepower4_pack_3_capacity"
    state_topic: "bms_lifepower4/pack_3/i_design_cap"
    unit_of_measurement: "Ah"

  - unique_id: "bms_lifepower4_pack_2_remain_capacity"
    name: "bms_lifepower4_pack_2_remain_capacity"
    state_topic: "bms_lifepower4/pack_2/i_remain_cap"
    unit_of_measurement: "Ah"

  - unique_id: "bms_lifepower4_pack_3_remain_capacity"
    name: "bms_lifepower4_pack_3_remain_capacity"
    state_topic: "bms_lifepower4/pack_3/i_remain_cap"
    unit_of_measurement: "Ah"

  - unique_id: "bms_lifepower4_pack_2_soh"
    name: "bms_lifepower4_pack_2_state_of_health"
    state_topic: "bms_lifepower4/pack_2/soh"

  - unique_id: "bms_lifepower4_pack_3_soh"
    name: "bms_lifepower4_pack_3_state_of_health"
    state_topic: "bms_lifepower4/pack_3/soh"

  - unique_id: "bms_lifepower4_pack_2_cycles"
    name: "bms_lifepower4_pack_2_cycles"
    state_topic: "bms_lifepower4/pack_2/cycles"

  - unique_id: "bms_lifepower4_pack_3_cycles"
    name: "bms_lifepower4_pack_3_cycles"
    state_topic: "bms_lifepower4/pack_3/cycles"

  - unique_id: "bms_lifepower4_pack_2_ambient_temp"
    name: "bms_lifepower4_pack_2_ambient_temp"
    state_topic: "bms_lifepower4/pack_2/temps/ambient_temp"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_3_ambient_temp"
    name: "bms_lifepower4_pack_3_ambient_temp"
    state_topic: "bms_lifepower4/pack_3/temps/ambient_temp"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_2_mos_temp"
    name: "bms_lifepower4_pack_2_mos_temp"
    state_topic: "bms_lifepower4/pack_2/temps/mos_temp"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_3_mos_temp"
    name: "bms_lifepower4_pack_3_mos_temp"
    state_topic: "bms_lifepower4/pack_3/temps/mos_temp"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_2_pack_temp_1"
    name: "bms_lifepower4_pack_2_pack_temp_1"
    state_topic: "bms_lifepower4/pack_2/temps/temp_1"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_3_pack_temp_1"
    name: "bms_lifepower4_pack_3_pack_temp_1"
    state_topic: "bms_lifepower4/pack_3/temps/temp_1"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_2_pack_temp_2"
    name: "bms_lifepower4_pack_2_pack_temp_2"
    state_topic: "bms_lifepower4/pack_2/temps/temp_2"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_3_pack_temp_2"
    name: "bms_lifepower4_pack_3_pack_temp_2"
    state_topic: "bms_lifepower4/pack_3/temps/temp_2"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_2_pack_temp_3"
    name: "bms_lifepower4_pack_2_pack_temp_3"
    state_topic: "bms_lifepower4/pack_2/temps/temp_3"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_3_pack_temp_3"
    name: "bms_lifepower4_pack_3_pack_temp_3"
    state_topic: "bms_lifepower4/pack_3/temps/temp_3"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_2_pack_temp_4"
    name: "bms_lifepower4_pack_2_pack_temp_4"
    state_topic: "bms_lifepower4/pack_2/temps/temp_4"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_3_pack_temp_4"
    name: "bms_lifepower4_pack_3_pack_temp_4"
    state_topic: "bms_lifepower4/pack_3/temps/temp_4"
    unit_of_measurement: "°C"

  - unique_id: "bms_lifepower4_pack_2_cell_1_volts"
    name: "bms_lifepower4_pack_2_cell_1_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_1"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_1_volts"
    name: "bms_lifepower4_pack_3_cell_1_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_1"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_2_volts"
    name: "bms_lifepower4_pack_2_cell_2_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_2"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_2_volts"
    name: "bms_lifepower4_pack_3_cell_2_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_2"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_3_volts"
    name: "bms_lifepower4_pack_2_cell_3_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_3"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_3_volts"
    name: "bms_lifepower4_pack_3_cell_3_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_3"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_4_volts"
    name: "bms_lifepower4_pack_2_cell_4_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_4"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_4_volts"
    name: "bms_lifepower4_pack_3_cell_4_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_4"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_5_volts"
    name: "bms_lifepower4_pack_2_cell_5_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_5"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_5_volts"
    name: "bms_lifepower4_pack_3_cell_5_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_5"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_6_volts"
    name: "bms_lifepower4_pack_2_cell_6_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_6"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_6_volts"
    name: "bms_lifepower4_pack_3_cell_6_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_6"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_7_volts"
    name: "bms_lifepower4_pack_2_cell_7_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_7"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_7_volts"
    name: "bms_lifepower4_pack_3_cell_7_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_7"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_8_volts"
    name: "bms_lifepower4_pack_2_cell_8_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_8"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_8_volts"
    name: "bms_lifepower4_pack_3_cell_8_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_8"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_9_volts"
    name: "bms_lifepower4_pack_2_cell_9_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_9"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_9_volts"
    name: "bms_lifepower4_pack_3_cell_9_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_9"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_10_volts"
    name: "bms_lifepower4_pack_2_cell_10_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_10"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_10_volts"
    name: "bms_lifepower4_pack_3_cell_10_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_10"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_11_volts"
    name: "bms_lifepower4_pack_2_cell_11_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_11"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_11_volts"
    name: "bms_lifepower4_pack_3_cell_11_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_11"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_12_volts"
    name: "bms_lifepower4_pack_2_cell_12_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_12"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_12_volts"
    name: "bms_lifepower4_pack_3_cell_12_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_12"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_13_volts"
    name: "bms_lifepower4_pack_2_cell_13_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_13"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_13_volts"
    name: "bms_lifepower4_pack_3_cell_13_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_13"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_14_volts"
    name: "bms_lifepower4_pack_2_cell_14_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_14"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_14_volts"
    name: "bms_lifepower4_pack_3_cell_14_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_14"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_15_volts"
    name: "bms_lifepower4_pack_2_cell_15_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_15"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_15_volts"
    name: "bms_lifepower4_pack_3_cell_15_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_15"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_2_cell_16_volts"
    name: "bms_lifepower4_pack_2_cell_16_volts"
    state_topic: "bms_lifepower4/pack_2/v_cells/cell_16"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"

  - unique_id: "bms_lifepower4_pack_3_cell_16_volts"
    name: "bms_lifepower4_pack_3_cell_16_volts"
    state_topic: "bms_lifepower4/pack_3/v_cells/cell_16"
    value_template: "{{ value | int / 1000 | round(2) }}"
    unit_of_measurement: "V"
